name: CI
run-name: ${{ github.actor }} is testing out o1js-blobstream
on: [push]
#on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  setup_node_and_rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - 
        name: Use Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - 
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Run e2e_risc_zero.sh
        working-directory: scripts/risc_zero_example/
        run: |
          bash ./e2e_risc_zero.sh

      - 
        name: Run e2e_blobstream_inclusion.sh
        working-directory: scripts/blobstream_example/
        run: |
          bash ./e2e_blobstream_inclusion.sh
